// Generated by scripts/export-abi.mjs from contracts/out/EpochLib.sol/EpochLib.json — do not edit.
export const EpochLibAbi = [
  {
    "type": "error",
    "name": "BeforeGenesis",
    "inputs": [
      {
        "name": "timestamp",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "genesis",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "ZeroEpochLength",
    "inputs": []
  }
] as const;
