// Generated by scripts/export-abi.mjs from contracts/out/FirsthandLens.sol/FirsthandLens.json — do not edit.
export const FirsthandLensAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "registry_",
        "type": "address",
        "internalType": "contract IPrincipalRegistry"
      },
      {
        "name": "anchors_",
        "type": "address",
        "internalType": "contract IPassportAnchors"
      },
      {
        "name": "grants_",
        "type": "address",
        "internalType": "contract IGrantManager"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "anchors",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IPassportAnchors"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "currentEpoch",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "domainSeparator",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "grantStatus",
    "inputs": [
      {
        "name": "grantId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "enum GrantStatus"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "grants",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IGrantManager"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "principalIsLive",
    "inputs": [
      {
        "name": "principalId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "registry",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IPrincipalRegistry"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "verify",
    "inputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct PassportLib.Passport",
        "components": [
          {
            "name": "h",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "origin",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "attest",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "termsHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "epoch",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "nonce",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "name": "",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct BatchProof",
        "components": [
          {
            "name": "index",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "siblings",
            "type": "bytes32[8]",
            "internalType": "bytes32[8]"
          }
        ]
      },
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      },
      {
        "name": "",
        "type": "uint8",
        "internalType": "enum VerifyFailure"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "error",
    "name": "NotImplemented",
    "inputs": [
      {
        "name": "feature",
        "type": "string",
        "internalType": "string"
      }
    ]
  }
] as const;
