// Generated by scripts/export-abi.mjs from contracts/out/MerkleLib.sol/MerkleLib.json — do not edit.
export const MerkleLibAbi = [
  {
    "type": "error",
    "name": "BatchTooLarge",
    "inputs": [
      {
        "name": "size",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "EmptyBatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "IndexOutOfRange",
    "inputs": [
      {
        "name": "index",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  }
] as const;
