// Generated by scripts/export-abi.mjs from contracts/out/PassportLib.sol/PassportLib.json — do not edit.
export const PassportLibAbi = [
  {
    "type": "error",
    "name": "InvalidSignatureLength",
    "inputs": [
      {
        "name": "length",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  }
] as const;
