#!/usr/bin/env node
/**
 * Exports contract ABIs from Foundry artifacts (contracts/out) to TypeScript `as const` modules under
 * contracts/abi so that viem/abitype can infer fully-typed contract calls.
 *
 * Usage: node scripts/export-abi.mjs   (run `forge build` first; `pnpm --filter @firsthand/contracts build` does both)
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "contracts", "out");
const ABI_DIR = join(ROOT, "contracts", "abi");

/** Public surface: deployable contracts plus the libraries whose custom errors clients decode. */
const CONTRACTS = [
  "PrincipalRegistry",
  "Rescissions",
  "PassportAnchorsBaseline",
  "PassportAnchorsPaged",
  "GrantManager",
  "ReceiptLedger",
  "RoyaltyRouter",
  "FirsthandLens",
  "HardwareDeviceRegistry",
  "SplitMath",
  "MerkleLib",
  "PassportLib",
  "EpochLib",
  "P256",
];
/** Test doubles whose ABI clients need on local chains. */
const DOUBLES = ["MockUSDC"];

function loadAbi(name) {
  const file = join(OUT, `${name}.sol`, `${name}.json`);
  if (!existsSync(file)) throw new Error(`missing artifact ${file} — run forge build`);
  return JSON.parse(readFileSync(file, "utf8")).abi;
}

mkdirSync(ABI_DIR, { recursive: true });
const indexLines = ["// Generated by scripts/export-abi.mjs — do not edit.", ""];
for (const name of [...CONTRACTS, ...DOUBLES]) {
  const abi = loadAbi(name);
  const body = `// Generated by scripts/export-abi.mjs from contracts/out/${name}.sol/${name}.json — do not edit.\nexport const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`;
  writeFileSync(join(ABI_DIR, `${name}.ts`), body);
  indexLines.push(`export { ${name}Abi } from "./${name}.js";`);
}
writeFileSync(join(ABI_DIR, "index.ts"), `${indexLines.join("\n")}\n`);
console.log(`✓ exported ${CONTRACTS.length + DOUBLES.length} ABIs to contracts/abi`);
